name: product_catalog
description: "A Product Catalog for Dunder Mifflin Paper Company, Inc."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  badges: ^3.1.2
  shimmer: ^3.0.0
  intl: ^0.18.1
  provider: ^6.1.1
  flutter_svg: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
     - images/
